---
- hosts: localhost
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
  - name: install python-software-properties
    apt:
      update_cache: yes
      name: python-software-properties
  - name: install nodejs ppa
    shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - name: install nodejs and npm
    apt:
      update_cache: yes
      name: nodejs
  - name: install python passlib
    apt:
      update_cache: yes
      name: python-passlib
  - name: install libpcap-dev
    apt:
      update_cache: yes
      name: "{{ item }}"
    with_items:
      - libpcap-dev
      - git
  - name: install nginx service
    apt:
      update_cache: yes
      name: nginx
  - name: install apache utils for htpasswd authentication for nginx
    apt:
      update_cache: yes
      name: apache2-utils
  - htpasswd:
      path: /etc/nginx/.htpasswd
      name: Compassys
      password: DNS
  - file: path=/etc/nginx/sites-available/default state=absent
  - copy:
      src: /home/ubuntu/dnscap/default
      dest: /etc/nginx/sites-available/default
  - copy:
      src: /home/ubuntu/dnscap/dns.js
      dest: /home/ubuntu/node_modules/decode/dns.js
      force: yes
  - service:
      name: nginx
      state: restarted
