---
- hosts: localhost
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
  - name: install nodejs
    apt:
      update_cache: yes
      name: nodejs-legacy
  - name: install npm
    apt:
      update_cache: yes
      name: npm
  - name: install python-passlib
    apt:
      update_cache: yes
      name: python-passlib
  - name: install libpcap-dev
    apt:
      update_cache: yes
      name: "{{ item }}"
    with_items:
      - libpcap-dev
      - git
  - name: install nginx service
    apt:
      update_cache: yes
      name: nginx
  - name: install apache utils for htpasswd authentication for nginx
    apt:
      update_cache: yes
      name: apache2-utils
  - git:
      repo: 'https://github.com/eabdul1127/dnscap.git'
      dest: /home/ubuntu/dnscap
  - htpasswd:
      path: /etc/nginx/.htpasswd
      name: Compassys
      password: DNS
  - file: path=/etc/nginx/sites-available/default state=absent
  - copy:
      src: /home/ubuntu/dnscap/default
      dest: /etc/nginx/sites-available/default
  - service:
      name: nginx
      state: restarted
